s3:
  bucket_name: unique-bucket-name-here

dynamodb:
  table_name: unique-bucket-name-here-s3-index
  billing_mode: PROVISIONED
  read_capacity: 5
  write_capacity: 5

lambda:
  reserved_concurrency: 10